name: student_grade_book
description: Gerenciador de notas de alunos - Funciona offline em Android e iOS
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  sqflite: ^2.3.0+1
  path_provider: ^2.1.0
  path: ^1.9.0
  image_picker: ^1.0.4
  image: ^4.1.1
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
